#!/usr/bin/env python
"""Generate the use-expdpy skill catalog and its copy-paste docs page.

Two derived artifacts, both committed and drift-checked:

* ``.claude/skills/use-expdpy/references/function-catalog.md`` - every public function,
  grouped by module, with its brief signature and one-line summary. Introspected from the
  installed library so it can never drift from the API.
* ``docs/use-with-llms.qmd`` - the hub page (the pyfixest ``skills.html`` analog): the
  machine-readable entry points, the MCP setup, and the full ``SKILL.md`` body embedded
  verbatim. All code fences are plain (display-only) so nothing executes at ``quarto render``.

``SKILL.md`` and the other reference files are hand-authored (their prose cannot be
introspected); a pytest asserts every function/topic name they mention is real.

Usage::

    pixi run -e docs python tools/build_use_skill.py          # (re)write both artifacts
    pixi run -e docs python tools/build_use_skill.py --check  # CI: fail on drift
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "tools"))

from build_llms_txt import doc_summary  # noqa: E402
from build_reference_enrichment import _brief_signature  # noqa: E402

import expdpy  # noqa: E402

SKILL_DIR = REPO / ".claude" / "skills" / "use-expdpy"
SKILL_MD = SKILL_DIR / "SKILL.md"
CATALOG = SKILL_DIR / "references" / "function-catalog.md"
HUB = REPO / "docs" / "use-with-llms.qmd"

BASE_URL = "https://cmg777.github.io/expdpy"
GITHUB_SKILL = "https://github.com/cmg777/expdpy/tree/main/.claude/skills/use-expdpy"

_GENERATED = "<!-- GENERATED by tools/build_use_skill.py - do not edit. -->"


def _catalog_line(name: str) -> str:
    obj = getattr(expdpy, name)
    return f"- `{name}{_brief_signature(obj)}` - {doc_summary(name)}"


def render_catalog() -> str:
    """Render the function catalog from ``expdpy.__all__`` and live signatures."""
    lines = [
        _GENERATED,
        "# expdpy function catalog",
        "",
        "Every public function, grouped by module, with its call signature and one-line "
        "summary. Generated from the installed library, so it is always current.",
        "",
    ]
    for title, prefix in (
        ("Explore", "explore_"),
        ("Analyze", "analyze_"),
        ("Learn", "learn_"),
    ):
        lines += [f"## {title}", ""]
        lines += [_catalog_line(n) for n in expdpy.__all__ if n.startswith(prefix)]
        lines.append("")

    lines += ["## Utilities", ""]
    for name in expdpy.__all__:
        obj = getattr(expdpy, name)
        if inspect.isfunction(obj) and not name.startswith(
            ("explore_", "analyze_", "learn_")
        ):
            lines.append(_catalog_line(name))
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _skill_body() -> str:
    """Return the SKILL.md body (frontmatter stripped)."""
    content = SKILL_MD.read_text()
    if content.startswith("---"):
        parts = content.split("---\n", 2)
        if len(parts) == 3:
            return parts[2].lstrip("\n")
    return content


_HUB_HEAD = f"""---
title: "expdpy for AI agents and LLMs"
---

{_GENERATED}
<!-- Source of truth: .claude/skills/use-expdpy/SKILL.md -->

expdpy ships first-class support for large language models and AI agents: a machine-readable
map of the library, function-calling schemas, an MCP server, and a portable agent skill. This
page is generated from the canonical skill, so it never drifts from what an agent receives.

## Machine-readable entry points

- [`/llms.txt`]({BASE_URL}/llms.txt) - a curated index of the whole library (the llmstxt.org
  convention), with expdpy's guardrails up front.
- [`/llms-full.txt`]({BASE_URL}/llms-full.txt) - every function, docstring and concept
  explainer concatenated into one file for full-context ingestion.
- [`/tools/anthropic_tools.json`]({BASE_URL}/tools/anthropic_tools.json) and
  [`/tools/openai_tools.json`]({BASE_URL}/tools/openai_tools.json) - curated function-calling
  tool schemas for the Anthropic and OpenAI APIs.
- Every docs page has a clean Markdown twin at `<page>.html.md`.

## MCP server

Install the optional extra and run the stdio server:

```bash
pip install "expdpy[mcp]"
```

Register it with an MCP client (Claude Desktop, Claude Code, ...):

```json
{{ "mcpServers": {{ "expdpy": {{ "command": "expdpy-mcp" }} }} }}
```

The server exposes a curated set of Explore/Analyze tools plus `explain` / `list_topics` /
`learn_concept`. Each tool returns the result's plain-language `interpret()` reading, its
tables, and a saved figure path.

## The use-expdpy agent skill

The skill below teaches an agent to use expdpy correctly. Copy the
[`.claude/skills/use-expdpy/`]({GITHUB_SKILL}) directory into your project (Claude Code reads
`.claude/skills/`), or paste the workflow below into your agent's instructions.

---

"""


def render_hub_page() -> str:
    """Render the docs hub page from the canonical SKILL.md (no executable cells)."""
    return _HUB_HEAD + _skill_body().rstrip() + "\n"


def _targets() -> dict[Path, str]:
    return {CATALOG: render_catalog(), HUB: render_hub_page()}


def main(argv: list[str] | None = None) -> int:
    """Write the catalog + hub page, or check them for drift with ``--check``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if either artifact differs from its regeneration.",
    )
    args = parser.parse_args(argv)
    targets = _targets()

    if args.check:
        stale = [
            path
            for path, text in targets.items()
            if not path.exists() or path.read_text() != text
        ]
        if stale:
            names = "\n".join(f"  - {p.relative_to(REPO)}" for p in stale)
            print(
                "Stale skill artifacts (run `python tools/build_use_skill.py`):\n"
                + names,
                file=sys.stderr,
            )
            return 1
        print("build_use_skill: catalog and hub page are up to date.")
        return 0

    for path, text in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    print(
        f"build_use_skill: wrote {CATALOG.relative_to(REPO)} and {HUB.relative_to(REPO)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
