#!/usr/bin/env python
"""Enrich quartodoc reference pages with a source link and executable examples.

quartodoc renders each function's docstring ``Examples`` as a *static* code block and offers no
"view source" link. This script post-processes the generated ``docs/reference/*.qmd`` pages so
that each one behaves like the splot reference the project mirrors:

* a **source** link is inserted just below the function name, pointing at the anchored source on
  the matching ``modules/`` source page (generated by :mod:`build_source_pages`);
* every example code block (the fenced blocks *after* the ``## Examples`` heading — never the
  signature block) is turned into an executable ``{python}`` cell, so its real output (an
  interactive Plotly figure, a Great Table, a DataFrame) renders directly below the code when
  Quarto runs the page;
* the reference **index** page gains a brief, splot-style argument signature beside each function
  name (``name(req[, opt, ...])``), so the listing shows what each function takes at a glance.

The reference directory is gitignored and regenerated on every build, so run this *after*
``quartodoc build`` / ``build_source_pages`` and *before* ``quarto render``::

    pixi run -e docs python tools/build_reference_enrichment.py
"""

from __future__ import annotations

import importlib
import inspect
import re
from pathlib import Path

from build_source_pages import NO_EXECUTE, load_doc_objects, source_link

REPO = Path(__file__).resolve().parents[1]
REFERENCE_DIR = REPO / "docs" / "reference"

# H1 of a generated page, e.g. ``# load_kuznets { #expdpy.data.load_kuznets }``.
_H1_RE = re.compile(r"^#\s+\S.*\{\s*#\s*([^}\s]+)\s*\}\s*$")
_EXAMPLES_RE = re.compile(r"^##\s+Examples\b", re.MULTILINE)
_FRONT_MATTER = "---\njupyter: python3\n---\n\n"

# An index-page table row: ``| [name](slug.qmd#fqn) | description |``. ``head`` is the cell up to
# the link's closing paren (where the brief signature is injected); ``rest`` is everything after.
_ROW_LINK_RE = re.compile(
    r"^(?P<head>\|\s*\[(?P<name>[^\]]+)\]\((?P<link>[^)]+)\))(?P<rest>.*)$"
)
_MAX_OPTIONAL = 2  # optional args named before the listing is truncated with ``...``


def _convert_example_fences(tail: str) -> tuple[str, int]:
    """Turn ```` ```python ```` example blocks into executable ```` ```{python} ```` cells.

    ``tail`` is the page text from the ``## Examples`` heading onwards. A block whose body holds
    a ``>>>`` line is a doctest: its prompt and expected-output lines are not valid Python, so it
    is left static rather than executed (which would abort the render).
    """
    lines = tail.split("\n")
    out: list[str] = []
    converted = 0
    i = 0
    while i < len(lines):
        if lines[i].rstrip() == "```python":
            close = i + 1
            while close < len(lines) and lines[close].rstrip() != "```":
                close += 1
            body = lines[i + 1 : close]
            unterminated = close >= len(lines)
            is_doctest = any(line.lstrip().startswith(">>>") for line in body)
            if unterminated or is_doctest:
                out.append(lines[i])
            else:
                out.append("```{python}")
                converted += 1
            out.extend(body)
            if not unterminated:
                out.append(lines[close])  # closing fence
            i = close + 1
        else:
            out.append(lines[i])
            i += 1
    return "\n".join(out), converted


def enrich_reference_text(
    text: str, source_url: str | None, *, executable: bool
) -> tuple[str, int]:
    """Insert the source link and (optionally) make the examples executable.

    Parameters
    ----------
    text
        The generated reference page.
    source_url
        Relative URL to the function's anchored source, or ``None`` to skip the link.
    executable
        When ``True``, convert the example code fences to executable ``{python}`` cells.

    Returns
    -------
    tuple[str, int]
        The rewritten page and the number of example fences that were made executable.
    """
    lines = text.split("\n")

    # 1. Insert the source link directly below the H1 (idempotent).
    if (
        source_url
        and ".viewcode-link" not in text
        and lines
        and lines[0].startswith("# ")
    ):
        link = f'[source]({source_url}){{.viewcode-link title="View source code"}}'
        lines[1:1] = ["", link]
    text = "\n".join(lines)

    # 2. Make the example blocks executable — only the fences after ``## Examples`` so the
    #    signature block (which precedes ``## Parameters``) is never executed.
    n_converted = 0
    if executable:
        match = _EXAMPLES_RE.search(text)
        if match:
            head, tail = text[: match.start()], text[match.start() :]
            tail, n_converted = _convert_example_fences(tail)
            text = head + tail

    # 3. A page with executable cells needs a Jupyter engine; add front matter once.
    if n_converted and not text.startswith("---"):
        text = _FRONT_MATTER + text

    return text, n_converted


def _resolve_fqn(fqn: str) -> object | None:
    """Import and return the object named by a fully-qualified name, or ``None``."""
    parts = fqn.split(".")
    for i in range(len(parts), 0, -1):
        try:
            obj: object = importlib.import_module(".".join(parts[:i]))
        except ImportError:
            continue
        try:
            for attr in parts[i:]:
                obj = getattr(obj, attr)
        except AttributeError:
            return None
        return obj
    return None


def _brief_signature(obj: object) -> str:
    """A splot-style call signature: ``(req[, opt1, opt2, ...])``, names only.

    Required parameters (no default, not ``*args``/``**kwargs``/``self``) are listed plainly;
    optional ones (with a default or keyword-only) are bracketed and truncated to the first
    ``_MAX_OPTIONAL`` names with a trailing ``...``. Returns ``""`` if introspection fails.
    """
    try:
        target = inspect.unwrap(obj)  # type: ignore[arg-type]
    except ValueError:
        target = obj
    try:
        sig = inspect.signature(target)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return ""

    required: list[str] = []
    optional: list[str] = []
    for name, p in sig.parameters.items():
        if name == "self" or p.kind in (p.VAR_POSITIONAL, p.VAR_KEYWORD):
            continue
        if p.default is not p.empty or p.kind == p.KEYWORD_ONLY:
            optional.append(name)
        else:
            required.append(name)

    inner = ", ".join(required)
    if optional:
        shown = ", ".join(optional[:_MAX_OPTIONAL])
        if len(optional) > _MAX_OPTIONAL:
            shown += ", ..."
        inner += f"[, {shown}]" if required else f"[{shown}]"
    return f"({inner})"


def enrich_index_text(text: str) -> tuple[str, int]:
    """Append a brief argument signature after each function link in the index tables.

    Each ``| [name](slug.qmd#fqn) | desc |`` row gains a ``<span class="doc-sig">(...)</span>``
    after the link (brackets escaped so Pandoc does not read them as a reference link). Header /
    separator rows, unresolvable names, and already-annotated rows are left unchanged.
    """
    out: list[str] = []
    annotated = 0
    for line in text.split("\n"):
        match = _ROW_LINK_RE.match(line)
        if not match or "doc-sig" in line or "#" not in match.group("link"):
            out.append(line)
            continue
        obj = _resolve_fqn(match.group("link").rsplit("#", 1)[-1])
        sig = _brief_signature(obj) if obj is not None else ""
        if not sig:
            out.append(line)
            continue
        escaped = sig.replace("[", "\\[").replace("]", "\\]")
        out.append(
            f'{match.group("head")}<span class="doc-sig">{escaped}</span>'
            f"{match.group('rest')}"
        )
        annotated += 1
    return "\n".join(out), annotated


def main() -> None:
    """Enrich every per-function reference page in place."""
    by_fqn = {obj.fqn: obj for obj in load_doc_objects()}

    pages = 0
    executed = 0
    for path in sorted(REFERENCE_DIR.glob("*.qmd")):
        text = path.read_text()
        first = text.split("\n", 1)[0]
        match = _H1_RE.match(first)
        if not match:
            continue  # index.qmd and other non-function pages
        obj = by_fqn.get(match.group(1))
        if obj is None:
            # A stale page from a renamed function (quartodoc never deletes these). It is not
            # in the navigation and would execute a now-missing example, so leave it untouched.
            continue
        pages += 1
        executable = obj.name not in NO_EXECUTE
        new_text, n = enrich_reference_text(
            text, source_link(obj), executable=executable
        )
        if new_text != text:
            path.write_text(new_text)
        executed += bool(n)

    # The index page (skipped above — its H1 has no ``{ #fqn }`` anchor) gets brief signatures.
    annotated = 0
    index_path = REFERENCE_DIR / "index.qmd"
    if index_path.exists():
        index_text = index_path.read_text()
        new_index, annotated = enrich_index_text(index_text)
        if new_index != index_text:
            index_path.write_text(new_index)

    print(
        f"build_reference_enrichment: enriched {pages} documented page(s) — "
        f"{executed} with executable examples; {annotated} index rows signed"
    )


if __name__ == "__main__":
    main()
